export const healthDataSourceCatalog = [
  { id: 'manual', label: 'Manual entry', kind: 'manual' },
  { id: 'seed', label: 'Seed data', kind: 'manual' },
  { id: 'apple_health', label: 'Apple Health', kind: 'platform' },
  { id: 'health_connect', label: 'Health Connect', kind: 'platform' },
  { id: 'fhir_import', label: 'FHIR import', kind: 'clinical_fhir' },
] as const;

export const healthMetricCatalog = [
  {
    key: 'blood_pressure_systolic',
    category: 'vital',
    label: 'Systolic blood pressure',
    valueKind: 'quantity',
    defaultUnit: 'mmHg',
    aggregationDefault: 'latest',
    loincCode: '8480-6',
  },
  {
    key: 'blood_pressure_diastolic',
    category: 'vital',
    label: 'Diastolic blood pressure',
    valueKind: 'quantity',
    defaultUnit: 'mmHg',
    aggregationDefault: 'latest',
    loincCode: '8462-4',
  },
  {
    key: 'heart_rate',
    category: 'vital',
    label: 'Pulse',
    valueKind: 'quantity',
    defaultUnit: 'bpm',
    aggregationDefault: 'latest',
    loincCode: '8867-4',
    appleIdentifier: 'heartRate',
    healthConnectRecordType: 'HeartRateRecord',
  },
  {
    key: 'resting_heart_rate',
    category: 'cardio',
    label: 'Resting heart rate',
    valueKind: 'quantity',
    defaultUnit: 'bpm',
    aggregationDefault: 'average',
    appleIdentifier: 'restingHeartRate',
    healthConnectRecordType: 'RestingHeartRateRecord',
  },
  {
    key: 'body_temperature',
    category: 'vital',
    label: 'Temperature',
    valueKind: 'quantity',
    defaultUnit: 'degF',
    aggregationDefault: 'latest',
    loincCode: '8310-5',
    appleIdentifier: 'bodyTemperature',
    healthConnectRecordType: 'BodyTemperatureRecord',
  },
  {
    key: 'oxygen_saturation',
    category: 'vital',
    label: 'O2 saturation',
    valueKind: 'percent',
    defaultUnit: '%',
    aggregationDefault: 'latest',
    loincCode: '2708-6',
    appleIdentifier: 'oxygenSaturation',
    healthConnectRecordType: 'OxygenSaturationRecord',
  },
  {
    key: 'respiratory_rate',
    category: 'vital',
    label: 'Respiratory rate',
    valueKind: 'quantity',
    defaultUnit: 'breaths/min',
    aggregationDefault: 'average',
    loincCode: '9279-1',
    appleIdentifier: 'respiratoryRate',
    healthConnectRecordType: 'RespiratoryRateRecord',
  },
  {
    key: 'body_weight',
    category: 'body',
    label: 'Weight',
    valueKind: 'quantity',
    defaultUnit: 'lb',
    aggregationDefault: 'latest',
    loincCode: '29463-7',
    appleIdentifier: 'bodyMass',
    healthConnectRecordType: 'WeightRecord',
  },
  {
    key: 'steps',
    category: 'activity',
    label: 'Steps',
    valueKind: 'count',
    defaultUnit: 'count',
    aggregationDefault: 'sum',
    appleIdentifier: 'stepCount',
    healthConnectRecordType: 'StepsRecord',
  },
  {
    key: 'active_minutes',
    category: 'activity',
    label: 'Active minutes',
    valueKind: 'duration',
    defaultUnit: 'min',
    aggregationDefault: 'sum',
    appleIdentifier: 'appleExerciseTime',
    healthConnectRecordType: 'ActiveCaloriesBurnedRecord',
  },
  {
    key: 'sleep_duration',
    category: 'sleep',
    label: 'Sleep',
    valueKind: 'duration',
    defaultUnit: 'min',
    aggregationDefault: 'duration',
    appleIdentifier: 'sleepAnalysis',
    healthConnectRecordType: 'SleepSessionRecord',
  },
  {
    key: 'time_in_bed',
    category: 'sleep',
    label: 'Time in bed',
    valueKind: 'duration',
    defaultUnit: 'min',
    aggregationDefault: 'duration',
    appleIdentifier: 'sleepAnalysis',
    healthConnectRecordType: 'SleepSessionRecord',
  },
  {
    key: 'heart_rate_variability_sdnn',
    category: 'cardio',
    label: 'HRV',
    valueKind: 'quantity',
    defaultUnit: 'ms',
    aggregationDefault: 'average',
    appleIdentifier: 'heartRateVariabilitySDNN',
    healthConnectRecordType: 'HeartRateVariabilityRmssdRecord',
  },
] as const;

export type HealthMetricKey = (typeof healthMetricCatalog)[number]['key'];
export type HealthDataSourceId = (typeof healthDataSourceCatalog)[number]['id'];
